package com.ld.validation;

public enum ValidationError {
    USER_ALREADY_REGISTERED,
    WRONG_USER_NAME_FORMAT,
    WRONG_PASSWORD_FORMAT,
    INCORRECT_PHONE_NUMBER,
    WRONG_TITLE_LENGTH,
    WRONG_DESCRIPTION_LENGTH,
    WRONG_ACCESS_TYPE;
}
